# MAIN INFO
site_name: OdooGPT
site_description: Make OdooBot finally useful!
site_url: https://odoogpt.thespino.dev

repo_name: thespino/odoogpt
repo_url: https://github.com/thespino/odoogpt

copyright: By @thespino


# THEME
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  custom_dir: custom
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - content.code.annotate
extra_css:
  - stylesheets/extra.css



# PLUGINS AND SETTINGS
plugins:
  - search
  # - privacy
  # privacy plugin needs insider - https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin
  # try this instead: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#additional-fonts

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list

extra:
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/linkedin
      link: https://go.thespino.dev/r/linkedin
    - icon: fontawesome/brands/instagram
      link: https://go.thespino.dev/r/instagram
    - icon: fontawesome/brands/facebook
      link: https://go.thespino.dev/r/facebook
    - icon: fontawesome/brands/youtube
      link: https://go.thespino.dev/r/youtube
    - icon: fontawesome/brands/github
      link: https://go.thespino.dev/r/github
    - icon: fontawesome/brands/mastodon
      link: https://go.thespino.dev/r/mastodon
    - icon: fontawesome/solid/globe
      link: https://thespino.dev
#   consent:
#     title: Cookie consent
#     description: >- 
#       We use cookies to recognize your repeated visits and preferences, as well
#       as to measure the effectiveness of our documentation and whether users
#       find what they're searching for. With your consent, you're helping us to
#       make our documentation better.


# PAGES, NAVIGATION
nav:
  - Home: index.md
  - Documentation:
    - 'Requirements': docs/requirements.md
    - 'Getting started': docs/getting-started.md
  - Video:
    - 'Configuration, Fine tune, Documentation for system administrators': video/sys-admin.md
  - About: about.md
